// Bakes the visitor card's three world maps from Natural Earth 1:110m land (public domain).
//
//   npm run gen:world [-- path/to/ne_110m_land.geojson]
//   (= node --import tsx scripts/gen-world.ts [path], from the repository root)
//
// Without a path it downloads the pinned release below. It writes the committed data: two
// modules under app/components/map/ (the dots and the globe, review treatments drawn in JS)
// and two static images under public/map/ (the shipped outline's land, and its sea and
// graticule). The images are drawn with no JavaScript at all: the card paints them as CSS
// masks in the server HTML (LocatorMap.tsx, globals.css "VISITOR CARD"), so the land is on
// screen with the card's first paint. Nothing here runs on the page, and no dependency is
// added: the projections come from app/lib/mapProjection.ts, the point-in-polygon test and
// the line simplifier are the dozen lines each below. Re-running on the same source is
// byte-identical; tests/world-data.test.ts holds the files to the page's frames, to one
// source hash, and to the land where the world keeps it.

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import {
  cellCentre,
  equalEarthFrame,
  millerGrid,
  packBits,
  sphereLattice,
  toEqualEarth,
} from "../app/lib/mapProjection";
import { DOTS_FRAME, GLOBE_STEP, OUTLINE_FRAME } from "../app/components/map/frames";

const SOURCE_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_110m_land.geojson";

// The parameters every consumer reads back from the data files.
// The frames are shared with the page (app/components/map/frames.ts); the sampling knobs are
// the generator's own.
export const PARAMS = {
  globe: { step: GLOBE_STEP, coverage: 0.34 },
  dots: { ...DOTS_FRAME, coverage: 0.4 },
  outline: { ...OUTLINE_FRAME, tolerance: 0.2, minArea: 1.2 },
} as const;

type Pt = [number, number]; // [lon, lat]
type Ring = { pts: Pt[]; minX: number; maxX: number; minY: number; maxY: number };

function ringOf(pts: Pt[]): Ring {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const [x, y] of pts) {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return { pts, minX, maxX, minY, maxY };
}

// Even-odd over every ring of every polygon: a hole (the Caspian) flips back to water.
function inside(rings: Ring[], lon: number, lat: number): boolean {
  let c = false;
  for (const r of rings) {
    if (lon < r.minX || lon > r.maxX || lat < r.minY || lat > r.maxY) continue;
    const p = r.pts;
    for (let i = 0, j = p.length - 1; i < p.length; j = i++) {
      const [xi, yi] = p[i];
      const [xj, yj] = p[j];
      if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) c = !c;
    }
  }
  return c;
}

// Fraction of an n×n sub-grid over [lon0, lon1] × [lat0, lat1] that is land — a dot is land
// when enough of its cell is, so a thin isthmus survives and a lone sample on a cape doesn't.
function coverage(rings: Ring[], lon0: number, lon1: number, lat0: number, lat1: number, n = 4): number {
  let hit = 0;
  for (let a = 0; a < n; a++)
    for (let b = 0; b < n; b++) {
      const lon = lon0 + ((a + 0.5) / n) * (lon1 - lon0);
      const lat = lat0 + ((b + 0.5) / n) * (lat1 - lat0);
      if (inside(rings, ((lon + 540) % 360) - 180, lat)) hit++;
    }
  return hit / (n * n);
}

function area(pts: Pt[]): number {
  let s = 0;
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) s += (pts[j][0] + pts[i][0]) * (pts[j][1] - pts[i][1]);
  return Math.abs(s / 2);
}

// Douglas–Peucker in degrees.
function simplify(pts: Pt[], tol: number): Pt[] {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack: [number, number][] = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop()!;
    const [ax, ay] = pts[a];
    const [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay;
    const len = Math.hypot(dx, dy) || 1;
    let best = -1, far = 0;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * (pts[i][0] - ax) - dx * (pts[i][1] - ay)) / len;
      if (d > far) { far = d; best = i; }
    }
    if (best > 0 && far > tol) {
      keep[best] = 1;
      stack.push([a, best], [best, b]);
    }
  }
  return pts.filter((_, i) => keep[i]);
}

// An SVG's provenance, as an XML comment (the same four facts as a module's header).
function svgFile(viewBox: string, sha: string, what: string, params: object, body: string): string {
  const note = [
    "AUTO-GENERATED by scripts/gen-world.ts - do not edit by hand; re-run the script.",
    `Source: Natural Earth 1:110m land (public domain), ${SOURCE_URL}`,
    `Source sha256: ${sha}`,
    what,
    `Parameters: ${JSON.stringify(params)}`,
  ].join("\n  ");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" preserveAspectRatio="none">\n<!--\n  ${note}\n-->\n${body}\n</svg>\n`;
}

// A polyline in one-decimal viewBox units.
function line(pts: { x: number; y: number }[]): string {
  return pts.map((p, i) => `${i ? "L" : "M"}${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join("");
}
const span = (a: number, b: number, n: number) => Array.from({ length: n + 1 }, (_, i) => a + ((b - a) * i) / n);

function header(sha: string, what: string, params: object): string {
  return [
    "// AUTO-GENERATED by scripts/gen-world.ts — do not edit by hand; re-run the script.",
    `// Source: Natural Earth 1:110m land (public domain), ${SOURCE_URL}`,
    `// Source sha256: ${sha}`,
    `// ${what}`,
    `// Parameters: ${JSON.stringify(params)}`,
    "",
  ].join("\n");
}

async function main() {
  const path = process.argv[2];
  const text = path ? readFileSync(path, "utf8") : await (await fetch(SOURCE_URL)).text();
  const sha = createHash("sha256").update(text).digest("hex");
  const geo = JSON.parse(text) as { features: { geometry: { type: string; coordinates: Pt[][] | Pt[][][] } }[] };
  const polys: Pt[][][] = [];
  for (const f of geo.features) {
    const g = f.geometry;
    if (g.type === "Polygon") polys.push(g.coordinates as Pt[][]);
    else if (g.type === "MultiPolygon") polys.push(...(g.coordinates as Pt[][][]));
  }
  const rings = polys.flat().map(ringOf);
  // Run from the repository root (npm scripts do); the modules land beside their treatments.
  const out = (name: string) => join(process.cwd(), "app/components/map", name);

  // GLOBE — one bit per sphereLattice dot.
  {
    const { step, coverage: cov } = PARAMS.globe;
    const lattice = sphereLattice(step);
    const bits = lattice.map(({ lon, lat }) => {
      const half = step / 2;
      const dl = half / Math.max(0.05, Math.cos((lat * Math.PI) / 180));
      return coverage(rings, lon - dl, lon + dl, lat - half, lat + half, 3) >= cov;
    });
    const land = bits.filter(Boolean).length;
    writeFileSync(
      out("worldGlobe.ts"),
      header(sha, `Globe: ${land} land dots of ${lattice.length} on mapProjection.sphereLattice(${step}), one bit each, MSB first.`, PARAMS.globe) +
        `export const GLOBE_DOTS = {\n  step: ${step},\n  count: ${lattice.length},\n  land: ${land},\n  bits: "${packBits(bits)}",\n} as const;\n`
    );
  }

  // DOTS — one bit per Miller grid cell, row-major.
  {
    const { cols, latTop, latBottom, coverage: cov } = PARAMS.dots;
    const g = millerGrid(cols, latTop, latBottom);
    const bits: boolean[] = [];
    for (let r = 0; r < g.rows; r++)
      for (let c = 0; c < g.cols; c++) {
        const a = cellCentre(g, c - 0.5, r - 0.5); // NW corner… (cellCentre of the half-shifted cell)
        const b = cellCentre(g, c + 0.5, r + 0.5); // …and SE corner
        bits.push(coverage(rings, a.lon, b.lon, b.lat, a.lat) >= cov);
      }
    const land = bits.filter(Boolean).length;
    writeFileSync(
      out("worldDots.ts"),
      header(sha, `Dots: ${land} land cells of ${g.cols}×${g.rows} on mapProjection.millerGrid(${cols}, ${latTop}, ${latBottom}), row-major, MSB first.`, PARAMS.dots) +
        `export const DOTS_GRID = {\n  cols: ${g.cols},\n  rows: ${g.rows},\n  latTop: ${latTop},\n  latBottom: ${latBottom},\n  land: ${land},\n  bits: "${packBits(bits)}",\n} as const;\n`
    );
  }

  // OUTLINE — Equal Earth, two static images at one viewBox: the land (integer units,
  // relative commands), and the sea (the cropped world's own outline: flat top and bottom,
  // curved sides) with a 30° graticule. Both are MASKS: only their alpha is read, and the
  // colours are the card's theme tokens (--vc-land; --vc-rule for the grid, the sea at 0.4
  // of it). Strokes are 1 CSS px at any size (non-scaling), as they were inline.
  {
    const { width, latTop, latBottom, tolerance, minArea } = PARAMS.outline;
    const f = equalEarthFrame(width, latTop, latBottom);
    const viewBox = `0 0 ${width} ${f.height.toFixed(1)}`;
    const P = (lon: number, lat: number) => toEqualEarth(f, lon, lat);
    let d = "";
    let kept = 0, points = 0;
    // Numbers self-delimit after a command letter or before a minus sign; otherwise a space.
    const num = (n: number) => (n < 0 || /[A-Za-z]$/.test(d) ? `${n}` : ` ${n}`);
    for (const poly of polys) {
      for (const ringPts of poly) {
        const r = ringOf(ringPts);
        if (r.maxY < latBottom || r.minY > latTop || area(ringPts) < minArea) continue;
        const pts = simplify(ringPts.slice(0, -1), tolerance);
        if (pts.length < 3) continue;
        kept++;
        let px = 0, py = 0;
        pts.forEach(([lon, lat], i) => {
          const p = P(lon, lat);
          const x = Math.round(p.x), y = Math.round(p.y);
          if (i === 0) {
            d += `M${x}`;
            d += `${num(y)}l`;
          } else if (x !== px || y !== py) {
            d += num(x - px);
            d += num(y - py);
          }
          px = x;
          py = y;
          points++;
        });
        d += "z";
      }
    }
    const pub = (name: string) => join(process.cwd(), "public/map", name);
    writeFileSync(
      pub("land.svg"),
      svgFile(viewBox, sha, `Land: ${kept} rings, ${points} points, Equal Earth ${width}x${Math.round(f.height)} (mapProjection.equalEarthFrame).`, PARAMS.outline, `<path d="${d}"/>`)
    );

    const sea = `${line([
      ...span(-180, 180, 2).map((lon) => P(lon, latTop)),
      ...span(latTop, latBottom, 48).map((lat) => P(180, lat)),
      ...span(180, -180, 2).map((lon) => P(lon, latBottom)),
      ...span(latBottom, latTop, 48).map((lat) => P(-180, lat)),
    ])}Z`;
    let grid = "";
    for (let lon = -150; lon <= 150; lon += 30) grid += line(span(latBottom, latTop, 32).map((lat) => P(lon, lat)));
    for (const lat of [-30, 0, 30, 60]) grid += line(span(-180, 180, 2).map((lon) => P(lon, lat)));
    const stroke = `stroke="#000" stroke-width="1" vector-effect="non-scaling-stroke"`;
    writeFileSync(
      pub("grid.svg"),
      svgFile(
        viewBox,
        sha,
        `Sea and graticule (30 deg): the frame's outline filled at 0.4 alpha, its edge and the grid lines at 1, Equal Earth ${width}x${Math.round(f.height)}.`,
        { width, latTop, latBottom },
        `<path d="${sea}" fill="#000" fill-opacity="0.4" ${stroke}/>\n<path d="${grid}" fill="none" ${stroke}/>`
      )
    );
  }
  console.log(`sha256 ${sha}`);
}

main();
